#Server Port
server:
  port: 8081

#Database Credentials
spring:
  application:
    name: ecommerce-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false

#Token Properties
jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration: 1800000

#Razorpay Properties
razorpay:
  key-id: rzp_test_TdNWU37S2ChC6s
  key-secret: xfcEQaX87hwMZhnceSa4Mc4G