#Server Port
server:
  port: 8081

#Database Credentials
spring:
  application:
    name: ecommerce-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

#Token Properties
jwt:
  secret: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  expiration: 1800000

razorpay:
  key-id: rzp_test_Td1F9V8Gt9r7pO
  key-secret: Or4Ks6j1WpKg7p5j1sUFcGmX